title: AI for Robotics Workshop 2024
description: Workshop on Recent Advancements of AI for Robotics, The Netherlands<br/><b>April 5th @ Tilburg, Netherlands</b><br/>Please register at <b><a style="color:#f0f0f0; text-decoration:underline" href="https://app.gomry.com/event/FymM05lNhqjfXlpddxgd">registration-link</a></b> if you plan to join us
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
