title: AI for Robotics Workshop 2024
description: Workshop on Recent Advancements of AI for Robotics, The Netherlands<br/><b>April 5th @ Tilburg, Netherlands</b><br/> <a style='color:#550000' href="https://youtu.be/r99hFpejUEU?si=Q6gjf1LGvkRaOFth">Youtube Recording</a> <br/> <a style='color:#550000' href="https://surfdrive.surf.nl/files/index.php/s/yAXGxNVoRwsOYHh">Photos of the event</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
