title: AI for Robotics Workshop 2024
description: Workshop on Recent Advancements of AI for Robotics, The Netherlands<br/><b>April 5th @ Tilburg, Netherlands</b><br/> <div style='color:#BFF'>Zoom Link: https://t.ly/pdto6 <br/> Youtube Streaming: https://www.youtube.com/watch?v=3NhOKsSWiOo <br/></div>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
